version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mininetumo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LAYSON2809
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mininetumo"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://postgres:LAYSON2809@db:5432/mininetumo
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
